version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wp
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA:
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );
        define( 'WP_DEBUG', true );
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: example


  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: example